### PR TITLE
remove micromatch, use metalsmith.match

### LINKED ISSUE #22: Remove micromatch, use metalsmith.match instead
* `npm remove micromatch`
* use `metalsmith.match`
* increment peerDependency `"metalsmith": "^2.4.1"`
* commit: `Resolves #<issue>: remove micromatch, use metalsmith.match`

### PR DESCRIPTION
**Pull request by RishiKumarRay**
Fixes #22

### CODE REVIEW

**Comment by webketje** [comment]
@RishiKumarRay Thank you, the package.json changes are ok. You forgot to edit `lib/index.js` though
https://github.com/metalsmith/remove/blob/master/lib/index.js#L1 needs to be removed
https://github.com/metalsmith/remove/blob/master/lib/index.js#L30 needs to be changed to `metalsmith.match(patterns, input)`

To keep the git history clean, you can make these changes locally, then use (so you can reuse the existing commit):
```bash
git commit --amend
git push --force origin master
````

**Comment by RishiKumarRay** [comment]
@webketje please review now

**Comment by webketje** [comment]
@RishiKumarRay index.js changes are not there? Did you forget to run `git add lib/index.js` before doing the other 2 commands?

**Comment by RishiKumarRay** [comment]
@webketje yeah sorry i forgot to add please check now

**Comment by webketje** [comment]
@RishiKumarRay

> https://github.com/metalsmith/remove/blob/master/lib/index.js#L1 needs to be removed (not replaced)

Also just noticed you forgot to increment the metalsmith peerDependency in `package.json` to `^2.4.1`

**Comment by RishiKumarRay** [comment]
@webketje actually i had updated but forgot to save that file but now seems everything is there. Thanks for sticking with my silly mistakes and letting me know

**Comment by webketje** [comment]
metalsmith.match is a core method, so there is no need to have "metalsmith.match": "^1.1.1", in the dependencies, it can be removed. see https://www.metalsmith.io/api/#Metalsmith+match)

It's also a good practice to run `npm test` before you commit to make sure that everything is working as intended.

**Comment by RishiKumarRay** [comment]
"dependencies": { 
    "debug": "^4.3.3"
  }
do i need to remove this too ? along with that , Also i ran npm test , all test are failing
Screenshot from 2022-02-07 14-14-38

**Comment by webketje** [comment]
@RishiKumarRay You forgot to assign the result to `const matches =  ...`: https://github.com/RishiKumarRay/remove/blob/master/lib/index.js#L29

**Comment by RishiKumarRay** [comment]
@webketje i have done this changes but the npm test is still failing

**Comment by webketje** [comment]
@RishiKumarRay I'm sorry, I forgot to add that metalsmith needed to be updated in devDependencies as well.
I cloned your fork, and it works with these changes:

```diff
diff --git a/lib/index.js b/lib/index.js
index 5f7ba5d..8b07869 100644
--- a/lib/index.js
+++ b/lib/index.js
@@ -26,7 +26,7 @@ function plugin(options) {
     options = options || {}
     const patterns = options.patterns || []

-    metalsmith.match(patterns, input)
+    const matches = metalsmith.match(patterns)
     debug('Marked %s files to remove', matches.length)

     matches.forEach((filename) => {
diff --git a/package.json b/package.json
index a8e7b40..98b5dc5 100644
--- a/package.json
+++ b/package.json
@@ -41,7 +41,7 @@
     "coveralls": "^3.1.1",
     "eslint": "^8.4.1",
     "eslint-config-prettier": "^8.3.0",
-    "metalsmith": "^2.3.0",
+    "metalsmith": "^2.4.1",
     "mocha": "^7.2.0",
     "nodemon": "^2.0.15",
     "nyc": "^15.1.0",
@@ -55,7 +55,6 @@
     "access": "public"
   },
   "dependencies": {
-    "metalsmith.match": "^1.1.1",
     "debug": "^4.3.3"
   }
 }
```

**Comment by webketje** [comment]
> @webketje actually i had updated but forgot to save that file but now seems everything is there. Thanks for sticking with my silly mistakes and letting me know

Given that the issue is labeled *good first issue*, the feature being added is as important as: you hopefully learning something about Git, NPM, Node, Metalsmith, and open-source conventions so you can contribute better, later 😄

**Comment by RishiKumarRay** [comment]
@webketje i have updated as stated also ran npm install then npm test but 4 tests are still failing , i don't know if this CI is going to run or not

**Comment by webketje** [comment]
@RishiKumarRay If the tests don't run locally, they will fail in CI.  You missed at line: https://github.com/RishiKumarRay/remove/blob/master/lib/index.js#L29. Please look **attentively** at the diff in my previous comment, you will see that your code is different.

**Comment by RishiKumarRay** [comment]
@webketje did it failed again ? it passed locally

**Comment by webketje** [comment]
Ah yes

> /home/travis/build/metalsmith/remove/lib/index.js
  2:9  error  'normalize' is assigned a value but never used  no-unused-vars

That require('path') line must be removed

**Comment by RishiKumarRay** [comment]
> Ah yes
> 
> > /home/travis/build/metalsmith/remove/lib/index.js
> > 2:9  error  'normalize' is assigned a value but never used  no-unused-vars
> 
> That require('path') line must be removed

removed whole line or only path word ?

**Comment by webketje** [comment]
Yes you can remove that line

**Comment by RishiKumarRay** [comment]
@webketje finally it passed :)

**Comment by RishiKumarRay** [comment]
@webketje i was looking at the -0.7% decrease in code coverage is it due this extra line ? line 58 in screenshot
Screenshot from 2022-02-07 23-04-46

**Comment by webketje** [comment]
@RishiKumarRay No, nothing to worry about. It's because the total # of lines of code decreased.  I will merge this PR as soon as I'm ready to publish a new version

**Pull request merged**
